### ISSUE TITLE
Agent Design

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#10]
Header|2nds
---|---
name| Agent Design
about| Guideline to follow in the development of the AI
title| Agent Design
labels| Sprint enhancement
assignees| Diego Cantu

### Description 
Start the design of our intelligent Agent using the selected language and the example AI as base guideline
---
### Acceptance criteria 
- [x] A document containing all the functions and diagrams for the AI

---

### Important details 
A language must already had been defined

---

### Priority
High
---

### ToDo
- [x] Create a draft of the things we need for the AI
- [x] Pass the requirements to UML format
