### ISSUE TITLE
Documentation of the selected AI

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#11]
Header|2nds
---|---
name| Documentation of the selected AI 
about| We will document the selected AI among the 4 researched AI
title| Documentation of the selected AI
labels| Sprint 1 enhancement
assignees| Hector Hernandez,Eduardo Ancira, Rolando Ruis, Diego Cantu

### Description 
Each team member is going to add documentation for AI it found how was made and how it accomplish an AI
---
### Acceptance criteria 
- [x] All files for the AI have comments of what it do 
- [X] The team members uploaded a documented AI version of the AI they had found

---

### Importante details 
The already has finished the issue Investigation of a Current AI that plays the selected E-Sport and it´s working with those files
---

### Priority
High
---

### ToDo
 - [x] Comment all AI files of what they do and how it´s made
 - [x] Upload the files in the correct folder of Github
