### ISSUE TITLE
Record videos 

### ISSUE THREAD

**Issue by Cupovboy** [ProyectoIntegrador2018/e_sports_ai#12]
Header|2nds
---|---
name| Record videos 
about| Record videos of the performance of the bot
title| Record videos 
labels| Sprint 3
assignees| Diego Cantu

### Description 
Record videos of the performance of the bot, showing the capabilities of it
---
### Acceptance criteria 
 - [x] Videos show what it´s happening in the match
- [x] The develop team can see what the bot it´s trying to accomplish
 - [x] The video isn´t of low quality

---

### Priority
Low
---

### ToDo
 - [x] Install a software to record the match vs the bot
 - [x] Setup of Dota 2 files for a match with the bot
 - [x] Scripts of the bot to see it´s perfomance
