### ISSUE TITLE
Jungle Objectives

### ISSUE THREAD

**Issue by eanciras** [ProyectoIntegrador2018/e_sports_ai#15]
Header|2nds
---|---
name| Jungle Objectives
about| The jungler bot would kill the jungle objective to help the team
title| Jungle Objectives
labels| enhancement
assignees| 

### Description 
As a jungler I will effectively create an advantage for my team by killing camps and jungle (forest) objectives
---
### Acceptance criteria 
The jungle will efficiently and effectively navigate the jungle (forest) and make the appropriate objectives according to the situation

- [ ] The bot correctly navigates the jungle
- [ ] The bot makes the appropriate camp or jungle objective 
- [ ] The bot shows in lane presence when required

---

### Important details 
This will only apply to the jungler as the jungler needs to navigate through the jungle (forest) instead of a lane and needs to kill camps instead of creeps
---

### Priority
High
---

### ToDo
- [ ] Create an appropriate navigation method for the jungles (mode_laning_”jungle chanp”.lua)
- [ ] Create an appropriate Bayesian network to define the nest bot objective in the jungle
