### ISSUE TITLE
Communication between bots

### ISSUE THREAD

**Issue by eanciras** [ProyectoIntegrador2018/e_sports_ai#16]
Header|2nds
---|---
name| Communication between bots
about| The bot can send message to others for help or joining a lane to win the game
title| Communication between bots
labels| enhancement
assignees| 

### Description 
As a bot I will effectively communicate, when my teammate receives my desire to do something
---
### Acceptance criteria 
The bot can send a message providing its team level desire and receive messages from other bots

- [ ] The bot correctly interprets the team desires
- [ ] The bot acts according to the team desires without neglecting its individual desires
- [ ]The bot actively participates in team decisions and objectives.

---

### Important details 
A desire is a value between 0 and 1 used to set the active mode of the bot. There are 2 types of desires, individual desires and team level desires.

---

### Priority
High
---

### ToDo
- [ ] Create a team level desires to handle team objectives
- [ ] Create a method in each bot to communicate with the team level desires handler
