### ISSUE TITLE
Learning using evolutionary algorithms

### ISSUE THREAD

**Issue by eanciras** [ProyectoIntegrador2018/e_sports_ai#17]
Header|2nds
---|---
name| Learning using evolutionary algorithms
about| The bot learns based on the evolutionary algorithm chosen
title| Learning using evolutionary algorithms
labels| enhancement
assignees| 

### Description 
As a bot I will learn after a match by adjusting my probability tables according to an evolutionary algorithm

---
### Acceptance criteria 
As a bot I will effectively learn when:
- [ ] I successfully finish a game (no matter if a win or a loss)
- [ ] According to an evolutive algorithm I produce sons or pass knowledge to future generations
- [ ] The learning curve after n generations shows signs of “learning” (win / loss ratio ~ 1

---

### Important details 
The evolutionary algorithm and any involved variables must be tested by the team individually
---

### Priority
Medium
---
### ToDo
- [ ] Define the evolutionary algorithm to be used
- [ ] Define a learning rate and the minimum accepted error (ej.: win/loss ratio > 0.97)
- [ ] Define a number of generations and population for the algorithm (take in consideration the length of the games)
- [ ] Implement and run the algorithm
