### ISSUE TITLE
Learning in-game

### ISSUE THREAD

**Issue by eanciras** [ProyectoIntegrador2018/e_sports_ai#18]
Header|2nds
---|---
name| Learning in-game
about| The bot learns using reinforcement learning for the probability of the mode it takes
title| Learning in-game
labels| enhancement
assignees| 

### Description 
As a bot I will learn by positive and negative reinforcement during a match by adjusting my probability tables
---
### Acceptance criteria 
As a bot I will effectively learn when:

- [ ] My probability tables at the end of the game are different from the ones at the beginning
- [ ] My probability tables change after every death downgrading the “bad choices”
- [ ] My probability tables change after every kill upgrading the “good choices” 
---
### Important details 
Good and Bad choices must be defined by the developing team. Suggested methods are to improve the probability of the mode the bot had when killing an enemy or downgrading the mode the bot had after dying.
---

### Priority
Medium
---
### ToDo
- [ ] Define the possible good and bad events that will trigger the probability change
- [ ] Define a learning rate for the bot
- [ ] Implement the learning method that will update the probability tables
