### ISSUE TITLE
Successful Farming (creep killing)

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#2]
Header|2nds
---|---
name| Successful Farming (creep killing) 
about| The bot can kill creeps and collect/farm money and experience to grow it´s level and skills
title| Successful Farming (creep killing)
labels| Sprint 3 enhancement
assignees| Rolando Ruiz

### Description 
Successful Farming (creep killing)
---
### Acceptance criteria 
As a bot I will successfully farm (kill) a creep when:

- [x] Dealt the final blow to the creep (the last killing hit on a creep)
- [x] Obtained killing gold

---

### Priority

Medium
---

### ToDo

- [x] detect the creep with lowest life in the area
- [x] attack a group of creeps
- [x] use skills on creeps
