### ISSUE TITLE
Tower Destroying

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#3]
Header|2nds
---|---
name| Tower Destroying
about| Description of the interaction that the user has with a certain functionality of the application.
title| Tower Destroying
labels| Sprint 3 enhancement
assignees| 

### Description 

---
### Acceptance criteria 
As a bot I will successfully destroy the Tower when

- [x] The tower I'm currently attacking loses all its resistance points
- [x] The tower effectively dissappears from the map

---

### Priority
Low
---

### ToDo
- [x] Make a script to attack the tower
- [x] Detect when to attack/use skills on the tower
- [x] detect when to retreat from the tower
