### ISSUE TITLE
Intelligent Navigation

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#4]
Header|2nds
---|---
name| Intelligent Navigation
about| Description of the interaction that the user has with a certain functionality of the application.
title| Intelligent Navigation
labels| Sprint 2 enhancement
assignees| Diego Cantu

### Description 
As a bot I will intelligently navigate the map when:
---
### Acceptance criteria 

- [x] I run towards priority objectives
- [x] I run away from danger when needed
---

### Important details 
The bot moves in the middle lane

---

### Priority
High
---

### ToDo
- [x] Define the functions needed for movements for the bot
- [x] Create an script for the navigation in the middle lane
