### ISSUE TITLE
Item Buying

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#5]
Header|2nds
---|---
name| Item Buying
about| Make a script that allow the AI buying from the Shop
title| Item Buying
labels| Sprint 2 enhancement
assignees| Rolando Ruiz

### Description 
Make a script that allow the AI buying from the Shop for it to use it in the match using the gold it has gained until that moment in the match
---
### Acceptance criteria 
As a bot I will successfully buy an item when:

- [x] I select the correct item to buy according to my character
- [x] I spend the appropriate amount of gold in such item
- [x] The item appears in my inventory.

---

### Priority
Medium
---

### ToDo
- [x] Make a script to buy items
- [x] Indicate how and where to buy the items
