### ISSUE TITLE
Efficient item using

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#6]
Header|2nds
---|---
name| Efficient item using
about| Description of the interaction that the user has with a certain functionality of the application.
title| Efficient item using
labels| sprint 3 ehancements
assignees| 

### Description 
As a bot I know when would be more uselful when and hoe to use an item to gain an edge in battle
---
### Acceptance criteria 
As a bot I will effectively use an item when:

- [x] The item's effects change the flow of battle (oppening an attack opportunity or an escape path)
- [x] The item or item's charges are removed from my inventory
- [x] The current battle (not game) is won or not lost due to the usage of such item

---
### Important details 
The items priority is decide in the current best strategy of time of creation (April 2019)
---

### Priority
High
---

### ToDo
- [x] Create the list of items to buy
- [x] Check the charges of the item
- [x] Check if it apropiate buying bases on lane status
- [x] Check if an items would help in recovering mana or health
