### ISSUE TITLE
Investigation of a Current AI that plays the selected E-Sport

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#7]
Header|2nds
---|---
name| Investigation of a Current AI that plays the selected E-Sport
about| As a member of the devopment tema I can check these files as a template for how an AI for Dota 2 was created
title| Investigation of a Current AI that plays the selected E-Sport
labels| Sprint 1 enhancement
assignees| Hector Hernandez,Eduardo Ancira, Rolando Ruis, Diego Cantu

### Description 
For research purposes we need to search for 4 different Intelligent Agents that play Dota2 which fulfills requirements:

- The Intelligent Agent must navigate the 
 map intelligently (engage and disengage objectives as needed)
- The Intelligent Agent must farm creeps efficiently (deal the final blow to a creep in order to obtain gold)
- The Intelligent Agent must buy and use items intelligently (buy the items that support their abilities and use them in the correct situations).
---
### Acceptance criteria 
 - [x] Found 4 different AI that play Dota 2
 - [x] Each AI fulfill the requirements

---

### Priority
High
---

### ToDo
- [x] Search either Steam workshop or Google an AI for Dota 2
 - [x] Check whether the AI fulfill the requirements
- [x] Check if the AI is different from the other team members
