### ISSUE TITLE
 E-Sports investigation

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#8]
Header|2nds
---|---
name| E-Sports investigation
about| Investigation to know if the E-sport is suitable as the environment for the AI
title| E-Sports investigation
labels| Sprint 1 enhancement
assignees| Eduardo Ancira

### Description 
Investigation about which E-Sport is the best to create a competitive AI. Following the characteristics of

- Base champions
- AI support
- Competitiveness
- Market Visibility
---
### Acceptance criteria 
- [x] Base champions document
- [x] AI support, Competitiveness, and Market Visibility document
---

### Important details 
The investigation was divided in two document, one for base champions of Dota 2 and the other containing the external factors of Dota 2

---

### Priority
Medium
---

### ToDo
- [x] Investigate the base champions of Dota 2
- [x] Investigate the external factors of the professional environment
