### ISSUE TITLE
Define language

### ISSUE THREAD

**Issue by rrprogramming** [ProyectoIntegrador2018/e_sports_ai#9]
Header|2nds
---|---
name| Define language 
about| Choose the languaje in which the AI would be developed 
title| Define language 
labels| Sprint 1 enhancement
assignees| 

### Description 
Definition of which of the following languages will be used to create the AI:

- Java
- LUA
- Phyton
---
### Acceptance criteria 
- [x] A Language has been defined 

---

### Priority
High
---

### ToDo
 - [x] Investigate in which languages has an AI been developed for Dota 2
- [x] Check the complexity of using that language
